// Generated by Wrangler by running `wrangler types`

interface Env {
	CLOUDFLARE_ACCOUNT_ID: string;
	CLOUDFLARE_DATABASE_ID: string;
	CLOUDFLARE_TOKEN: string;
	BETTER_AUTH_SECRET: string;
	BETTER_AUTH_URL: string;
	OAUTH_GITHUB_CLIENT_ID: string;
	OAUTH_GITHUB_CLIENT_SECRET: string;
	DB: D1Database;
}
